# Output goes here, this folder is cleared on each run
# Absolute path or relative to the folder containing this file
target-folder: "c"

# Folder where things go for deployment, relative to project folder
deploy-folder: _output/folien-r/c

# Jobs
jobs:
- copy:
  from: style.scss
  to: ${target-folder}/style.scss
- copy:
  from: quarto-template.yml
  to: ${target-folder}/_metadata.yml

# Jobs running on all parts
jobs-on-parts:

# Copy into target folder (web access)
- copy:
  from: ${part-folder}/folien.qmd
  to: ${target-folder}/${idx}-${name}.qmd
- copy:
  from: ${part-folder}/bilder
  to: ${target-folder}/bilder
  optional: yes
  exclude-patterns: [".afdesign$"]
- copy:
  from: ${part-folder}/daten
  to: ${target-folder}/daten
  optional: yes
- copy:
  from: ${part-folder}/skripte
  to: ${target-folder}/skripte
  optional: yes

# Into subfolders of target folder to be zipped and deleted. Zipfile
# for download from Moodle
- copy:
  from: ${part-folder}/folien.qmd
  to: ${target-folder}/${idx}-${name}/${name}.qmd
- copy:
  from: ${part-folder}/folien.Rproj
  to: ${target-folder}/${idx}-${name}/${name}.Rproj
- copy:
  from: ${part-folder}/bilder
  to: ${target-folder}/${idx}-${name}/bilder
  optional: yes
  exclude-patterns: [".afdesign$"]
- copy:
  from: ${part-folder}/daten
  to: ${target-folder}/${idx}-${name}/daten
  optional: yes
- copy:
  from: ${part-folder}/skripte
  to: ${target-folder}/${idx}-${name}/skripte
  optional: yes
- copy:
  from: quarto-template.yml
  to: ${target-folder}/${idx}-${name}/_quarto.yml
- copy:
  from: style.scss
  to: ${target-folder}/${idx}-${name}/style.scss
- zip:
  zipfile: ${idx}-${name}.zip
  folder: ${idx}-${name}
  root: ${target-folder}
- copy:
  from: ${target-folder}/${idx}-${name}.zip
  to: ${deploy-folder}/${idx}-${name}.zip
  overwrite: yes
- delete:
  folder: ${target-folder}/${idx}-${name}

# Pattern to extract name from part folder
part-name-pattern: "w\\-(.*)/"

# Parts, folders relative to project root
parts:
- folder: bausteine/bcd-bausteine-r/w-erste-schritte/folien
- folder: bausteine/bcd-bausteine-r/w-ggplot2/folien
- folder: bausteine/bcd-bausteine-r/w-einzelne-merkmale/folien
- folder: bausteine/bcd-bausteine-r/w-kenngroessen/folien
- folder: bausteine/bcd-bausteine-r/w-dichtekurven-und-normalverteilung/folien
- folder: bausteine/bcd-bausteine-r/w-zwei-merkmale/folien
- folder: bausteine/bcd-bausteine-r/w-weitere-geoms-und-plots-aufbereiten/folien
- folder: bausteine/bcd-bausteine-r/w-grundlagen-r/folien
- folder: bausteine/bcd-bausteine-r/w-daten-einlesen/folien
- folder: bausteine/bcd-bausteine-r/w-daten-aufbereiten/folien
