project:
  type: book
  output-dir: ../../_output/skript

lang: de
number-depth: 2

book:
  title: "Mathematik B"
  subtitle: Statistik und Datenanalyse
  author: "Matthias Baitsch"
  output-file: skript-mathematik-b
  date: today
  chapters:
    - index.qmd
    - part: Beschreibende Statistik
      chapters:
        - c/01-statistische-daten.qmd
        - c/02-einzelne-merkmale.qmd
        - c/03-kenngroessen.qmd
        - c/04-dichtekurven-und-normalverteilung.qmd
        - c/05-zwei-merkmale.qmd
    - part: Wahrscheinlichkeitstheorie
      chapters:
        - c/06-grundbegriffe-wahrscheinlichkeitsrechnung.qmd
        - c/07-wahrscheinlichkeit.qmd
        - c/08-kombinatorik.qmd
        - c/09-rechnen-mit-wahrscheinlichkeiten.qmd
        - c/10-zufallsvariablen.qmd
        - c/11-zuverlaessigkeit-von-tragwerken.qmd
    - part: Schließende Statistik
      chapters:
        - c/12-schliessende-statistik.qmd
    - literatur.qmd

filters: 
  - latex-environment
commands:
  - neuerbegriff
environments:
  - beispiel

format: 
  html: 
    toc: true
    toc-depth: 4
    license: CC BY-SA
    css: bcd-style-notes.css
    default-image-extension: svg
    format-links:
      - pdf
  pdf:
    include-in-header:
      - _bcd-setup.tex
      - text: |
          \AddToHook{cmd/section/before}{\clearpage}
    include-after-body:
      text: |
        \printindex
    default-image-extension: pdf
    
bibliography: bcd-bausteine-statistik.bib

