target-folder: c
deploy-folder: _output/aufgaben/c

definitions:

- assignment-header: |
    ---
    title: "Aufgabenblatt ${sidx}"
    subtitle: "${subtitle}"
    ---

- assignment-solution-header: |
    ---
    title: "Lösungen zu Aufgabenblatt ${sidx}"
    subtitle: "${subtitle}"
    ---


jobs:

#
# 1. Statistische Daten
- assignment-paper:
  subtitle: "Statistische Daten"
  sol: 6ou3wer
  files: 
  - ${project-folder}/bausteine/bcd-bausteine-statistik/m-statistische-daten/aufgaben/*.qmd
- copy:
  from: ${project-folder}/bausteine/bcd-bausteine-statistik/m-statistische-daten/aufgaben/00-bilder
  to: ${target-folder}/00-bilder
- copy:
  from: ${project-folder}/bausteine/bcd-bausteine-statistik/m-statistische-daten/aufgaben/01-daten
  to: ${target-folder}/01-daten
- increment-index:

#
# 2. Einzelne Merkmale
- assignment-paper:
  subtitle: "Untersuchung einzelner Merkmale"
  sol: 834hja1
  files: 
  - ${project-folder}/bausteine/bcd-bausteine-statistik/m-einzelne-merkmale/aufgaben/*.qmd    
  - ${project-folder}/bausteine/bcd-bausteine-r/w-einzelne-merkmale/aufgaben/10.*.qmd
# Projekt für Studierende TODO make it a job
- copy: 
  from: ${project-folder}/bausteine/bcd-bausteine-r/w-einzelne-merkmale/aufgaben/aufgaben.qmd
  to: ${target-folder}/${idx}-einzelne-merkmale-aufgaben/einzelne-merkmale-aufgaben.qmd
- copy: 
  from: ${project-folder}/bausteine/bcd-bausteine-r/w-einzelne-merkmale/aufgaben/aufgaben.Rproj
  to: ${target-folder}/${idx}-einzelne-merkmale-aufgaben/einzelne-merkmale-aufgaben.Rproj
- copy: 
  from: ${project-folder}/bausteine/bcd-bausteine-r/w-einzelne-merkmale/aufgaben/daten
  to: ${target-folder}/${idx}-einzelne-merkmale-aufgaben/daten
- copy: 
  from: ${project-folder}/folien-r/style.scss
  to: ${target-folder}/${idx}-einzelne-merkmale-aufgaben/style.scss
- copy: 
  from: ${project-folder}/folien-r/quarto-template.yml
  to: ${target-folder}/${idx}-einzelne-merkmale-aufgaben/_quarto.yml
- zip:
  zipfile: ${idx}-einzelne-merkmale-aufgaben.zip
  folder: ${idx}-einzelne-merkmale-aufgaben
  root: ${target-folder}
- copy:
  from: ${target-folder}/${idx}-einzelne-merkmale-aufgaben.zip
  to: ${deploy-folder}/${idx}-einzelne-merkmale-aufgaben.zip
  overwrite: yes
# Fertig
- increment-index:

#
# 3. Kenngrößen
- assignment-paper:
  subtitle: "Kenngrößen und Beschreibung von Verteilungen"
  sol: kjdf784
  files: 
  - ${project-folder}/bausteine/bcd-bausteine-statistik/m-kenngroessen/aufgaben/*.qmd    
  - ${project-folder}/bausteine/bcd-bausteine-r/w-kenngroessen/aufgaben/10.*.qmd
- copy:
  from: ${project-folder}/bausteine/bcd-bausteine-statistik/m-kenngroessen/aufgaben/00-bilder
  to: ${target-folder}/00-bilder
# Projekt für Studierende TODO make it a job
- copy: 
  from: ${project-folder}/bausteine/bcd-bausteine-r/w-kenngroessen/aufgaben/aufgaben.qmd
  to: ${target-folder}/${idx}-kenngroessen-aufgaben/kenngroessen-aufgaben.qmd
- copy: 
  from: ${project-folder}/bausteine/bcd-bausteine-r/w-kenngroessen/aufgaben/aufgaben.Rproj
  to: ${target-folder}/${idx}-kenngroessen-aufgaben/kenngroessen-aufgaben.Rproj
- copy: 
  from: ${project-folder}/bausteine/bcd-bausteine-r/w-kenngroessen/aufgaben/daten
  to: ${target-folder}/${idx}-kenngroessen-aufgaben/daten
- copy: 
  from: ${project-folder}/folien-r/style.scss
  to: ${target-folder}/${idx}-kenngroessen-aufgaben/style.scss
- copy: 
  from: ${project-folder}/folien-r/quarto-template.yml
  to: ${target-folder}/${idx}-kenngroessen-aufgaben/_quarto.yml
- zip:
  zipfile: ${idx}-kenngroessen-aufgaben.zip
  folder: ${idx}-kenngroessen-aufgaben
  root: ${target-folder}
- copy:
  from: ${target-folder}/${idx}-kenngroessen-aufgaben.zip
  to: ${deploy-folder}/${idx}-kenngroessen-aufgaben.zip
  overwrite: yes
# Fertig
- increment-index:

