target-folder: c
deploy-folder: _output/aufgaben/c


# Global variable definitions
definitions:

- bcd-bausteine-r: ${project-folder}/bausteine/bcd-bausteine-r
- bcd-bausteine-statistik: ${project-folder}/bausteine/bcd-bausteine-statistik

- assignment-header: |
    ---
    title: "Aufgabenblatt ${sidx}"
    subtitle: "${subtitle}"
    ---

- assignment-solution-header: |
    ---
    title: "Lösungen zu Aufgabenblatt ${sidx}"
    subtitle: "${subtitle}"
    ---


# Individual jobs
jobs:

# 01
- assignment-paper:
  subtitle: "Statistische Daten"
  sol: 6ou3wer
  files: 
  - ${bcd-bausteine-statistik}/m-statistische-daten/aufgaben/*.qmd
  folders:
  - ${bcd-bausteine-statistik}/m-statistische-daten/aufgaben/*
- increment-index:

# 02
- assignment-paper:
  subtitle: "Untersuchung einzelner Merkmale"
  sol: 834hja1
  files: 
  - ${bcd-bausteine-statistik}/m-einzelne-merkmale/aufgaben/*.qmd    
  - ${bcd-bausteine-r}/w-einzelne-merkmale/aufgaben/10.*.qmd
  folders:
  - ${bcd-bausteine-statistik}/m-einzelne-merkmale/aufgaben/*
- increment-index:

# 03
- assignment-paper:
  subtitle: "Kenngrößen und Beschreibung von Verteilungen"
  sol: kjdf784
  files: 
  - ${bcd-bausteine-statistik}/m-kenngroessen/aufgaben/*.qmd    
  - ${bcd-bausteine-r}/w-kenngroessen/aufgaben/10.*.qmd
  folders:
  - ${bcd-bausteine-statistik}/m-kenngroessen/aufgaben/*
- increment-index:

# 04
- assignment-paper:
  subtitle: "Dichtekurven und Normalverteilung"
  sol: oa34alf
  files: 
  - ${bcd-bausteine-statistik}/m-dichtekurven-und-normalverteilung/aufgaben/*.qmd    
  - ${bcd-bausteine-r}/w-dichtekurven-und-normalverteilung/aufgaben/10.*.qmd
  folders:
  - ${bcd-bausteine-statistik}/m-dichtekurven-und-normalverteilung/aufgaben/*
- increment-index:

# 05
- assignment-paper:
  subtitle: "Untersuchung von zwei Merkmalen"
  sol: iuzert4
  files: 
  - ${bcd-bausteine-statistik}/m-zwei-merkmale/aufgaben/01.*.qmd    
  - ${bcd-bausteine-r}/w-zwei-merkmale/aufgaben/10.*.qmd
  - ${bcd-bausteine-statistik}/m-zwei-merkmale/aufgaben/0[2-4].*.qmd    
  - ${bcd-bausteine-r}/w-zwei-merkmale/aufgaben/20.*.qmd
  folders:
  - ${bcd-bausteine-statistik}/m-zwei-merkmale/aufgaben/*
  - ${bcd-bausteine-r}/w-zwei-merkmale/aufgaben/bilder
- increment-index:

# 06
- assignment-paper:
  subtitle: "Plots aufbereiten und Grundlagen R"
  sol: 7aesh3y
  files: 
  - ${bcd-bausteine-r}/w-weitere-geoms-und-plots-aufbereiten/aufgaben/10.*.qmd
  - ${bcd-bausteine-r}/w-grundlagen-r/aufgaben/10.*.qmd
  folders:
  - ${bcd-bausteine-r}/w-weitere-geoms-und-plots-aufbereiten/aufgaben/*
  - ${bcd-bausteine-r}/w-grundlagen-r/aufgaben/*
- increment-index:

# Jobs to run on the parts
jobs-on-parts:
- copy: 
  from: ${part-folder}/aufgaben.qmd
  to: ${target-folder}/${idx}-${name}-aufgaben/${name}-aufgaben.qmd
- copy: 
  from: ${part-folder}/aufgaben.Rproj
  to: ${target-folder}/${idx}-${name}-aufgaben/${name}-aufgaben.Rproj
- copy: 
  from: ${part-folder}/daten
  to: ${target-folder}/${idx}-${name}-aufgaben/daten
  optional: yes
- copy: 
  from: ${project-folder}/folien-r/style.scss
  to: ${target-folder}/${idx}-${name}-aufgaben/style.scss
- copy: 
  from: ${project-folder}/folien-r/quarto-template.yml
  to: ${target-folder}/${idx}-${name}-aufgaben/_quarto.yml
- zip:
  zipfile: ${idx}-${name}-aufgaben.zip
  folder: ${idx}-${name}-aufgaben
  root: ${target-folder}
- copy:
  from: ${target-folder}/${idx}-${name}-aufgaben.zip
  to: ${deploy-folder}/${idx}-${name}-aufgaben.zip
  overwrite: yes


# Pattern to extract name from part folder
part-name-pattern: "w\\-(.*)/"


# Parts, folders relative to project root
parts:
- folder: skip
- folder: bausteine/bcd-bausteine-r/w-einzelne-merkmale/aufgaben
- folder: bausteine/bcd-bausteine-r/w-kenngroessen/aufgaben
- folder: bausteine/bcd-bausteine-r/w-dichtekurven-und-normalverteilung/aufgaben
- folder: bausteine/bcd-bausteine-r/w-zwei-merkmale/aufgaben
- folder: bausteine/bcd-bausteine-r/w-weitere-geoms-und-plots-aufbereiten/aufgaben
- folder: bausteine/bcd-bausteine-r/w-grundlagen-r/aufgaben
