on:
  push:
    branches: main

name: Render and publish

jobs:
    
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render and publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: skript
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
