on:
  push:
    branches: main

name: Render

jobs:
    
  build:

    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render
        run: |
          cd skript && quarto render

